### ISSUE TITLE
ktkimura

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#116]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by ktkimura** [comment]
Hello! My name is Katie, and I'm a 3rd year Computer Science student at Oregon State University. I'm exploring OSSDoorway for research purposes.

**Comment by ktkimura** [comment]
Hi @caiton1, as a frequent contributor to this rep, would you happen to have any advice on solving this issue? Thanks in advance for your time!

**Comment by ktkimura** [comment]
This issue has been resolved. Thanks to all who contributed!
