### ISSUE TITLE
divyatirumalakorrapati

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#26]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by Divyatirumalakorrapati** [comment]
Hi @caiton1 

I am Divya Tirumala Korrapati. I'm focused on a specific issue in the JabRef project and have noticed that you've made the most contributions to it. Your extensive involvement suggests you have valuable insights that could greatly enhance my proposal. I would appreciate any advice you could offer to make the README clearer and more accessible to everyone. Thank you in advance for your guidance. I look forward to working with you and the rest of the community to implement this improvement.

**Comment by Divyatirumalakorrapati** [comment]
@connman4027 please help me to close this issue

**Comment by Divyatirumalakorrapati** [comment]
updated readme by #14

**Comment by Divyatirumalakorrapati** [comment]
Updated readme by contributing with better understanding #50
