### ISSUE TITLE
sangeetha-nakkala

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#36]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by sangeetha-nakkala** [comment]
Sure, here's a different version of your introduction:

---

Hi everyone,

I'm Sangeetha Reddy Nakkala, a master’s student in computer science at NAU. I have a strong interest in automation script development, data analytics, project management organization, and software development. I signed up for this class to learn how to contribute to open source projects and to gain practical experience in solving real-world problems. I hope to learn a lot from this course and become proficient by the end. This course will teach me how to start new projects, collaborate with others, and get involved with existing open source software projects.

I look forward to working with all of you! Thank you.

**Comment by sangeetha-nakkala** [comment]
Hello @caiton1 ,

 I hope you’re well. I wanted to ask you for help with issue #36. I have found your feedback so helpful on my project and I think your input on this could help me to clarify the writing for the documentation. Do you think there was a clearer way I could’ve phrased the Contributing section in the Readme file? I appreciate your input. Your feedback will make the project more approachable for beginners.

 Thank you for reading my request and for the strong work you do. I look forward to hearing from you. 

Best regards,
Sangeetha Reddy Nakkala
