### ISSUE TITLE
Tanujasontakke

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#37]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by Tanujasontakke** [comment]
Hello everyone,

I'm Tanuja Sontakke, master’s student in computer science. I have interest in artificial intelligence, data analytics, and software development.  I joined this class to learn how to contribute to open source projects and gain practical experience in solving real-world problems. My goal is to become proficient by the end of the course and learn how to collaborate with others on interesting open source project.

Thank you,
Tanuja

**Comment by Tanujasontakke** [comment]
@caiton1, Thank you for all the assistance provided, can you please let me know more on this issue?
