### ISSUE TITLE
kkarissa

### ISSUE THREAD

**Issue by caiton1** [NAU-OSS/jabref#60]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by kkarissa** [comment]
Hello! My name is Karissa, I have some understanding of how GitHub works! I am excited to help on any issue no matter how big or small! I hope by doing this I can expand my knowledge on GitHub even more!

Thank You!

**Comment by kkarissa** [comment]
@caiton1 would you mine providing some help on this issue? Any information would be very helpful! Thank you so much!
