### ISSUE TITLE
niteflyunicorns

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#67]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by niteflyunicorns** [comment]
Hi there, I am Savannah. I am a second-year masters student in computer science. My background is in animation and mathematics, and I eventually want to work in astronomy visualization as a career. I am looking forward to learning more about contributing to open source this semester!
