### ISSUE TITLE
nikhilmodem

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#76]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by nikhilmodem** [comment]
Hello, my name's Nikhil Modem. Im a computer science graduate student. I find this project particular interesting because of the technology it's serving. I want to contribute towards this issue as it can make a significant difference. I wonder who wrote the the previous versions of this code.

**Comment by nikhilmodem** [comment]
I thank you for everyone's contribution and efforts.
