### ISSUE TITLE
cnorteye

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#77]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by cnorteye** [comment]
Hello my name is Comfort. I am interested in increasing my knowledge and understanding of open-source and of using git& github. I don't have any questions, but I hope to improve my skills by contributing to this project.

**Comment by cnorteye** [comment]
@caiton1 can you help provide me with some guidance on how to complete this issue? Thank you for our help
