### ISSUE TITLE
acpaquette

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#79]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by acpaquette** [comment]
Hi all, I am a developer from the USGS and am interested in contributing to the software as it seems like a good fit for managing bibliographies in research papers.

**Comment by acpaquette** [comment]
@caiton1 Could you provide some insight into how the contributors section could either be rearranged or updated to further increase clarity? Is there any section in particular people are getting lost in?

**Comment by acpaquette** [comment]
Closed by #102
